env:
  global:
  - secure: nmJKkHXADOoPQfEjaGo+oN0aJ9ysJ9phVp4cW0RgceM+MnwXduUdaFIc3hrP2RhdJhxj1yji+8dm5Cr0vr4HvKZs21Ng4dHX+x2KTCFaxKX4qh+Xr7KA4dTToLMGit6liKJtO9OMk8O0co0NK7RVUMfaIH8+C5M6O1G1ysuy3gMchtFG2Lnmi0FKGeLKuenKLk1Wgb8EiYH4l9OanyV3NQ4Ea2/l3r0XgYjaWHvEu+Fr9q4IdS7a+c2AwztDJmvs3rAnaG2yTeyquOWyTCRVNi5yMm9/xnocOz7i1dqW7MSFU1NPUUPaYZGwPnVIjYoDTgtkR0S80Zpm4qqLtr/Qv9A0MfWi+3ftqZtAE9jjxhrMe4bEFVK1iBnE+xGpwrIrAQv4nevoM7OK6RJ/8rqvdfLD8sNOLsyXTlwILIXluMbZX93kpdVl9tcyUkOCeeoGzSY/i74Y+gnHtKozioeP6BX/O3Ov+V+NRqtaXxPCrEUk7QW1UTk5R1lNtJQHipr5Nze2QjEbbGaOYKU0kFkynlFvRvoXw2hZfdMAUIjKmqBA5UxARYWXve2UNRPcFHrfNiESpV0L4fHxqpHGPp0UGuirzwgKYJWIJId+7vd3e5rGS+JtBRiwfx4H/1H8tjKE4XLTIORXRJLWVrBDEbkf7Z5XYyyohLMd2XH+YlEw6kk=
  - secure: CAMnRWopXQ8ews94NsseBgeV/x2nTVPa5IGCf4mgNAPd8F7ASrBGLegs9wzzX78fMMpZZqG10uA6B5x4X0lloId1qtBqbGn8fB6j038550EtJ39r79PmtUliVYqPKPO9EehjzyrC2RldiZhln16QRfuc0xBqYnyq6psVNWYDOO6Se3HrIAHwzc8BcQN8MbkncnB91vPBG/WF8ynBrQblw+GzQ7lbuvtrZT86ZGf1qk1mrGeUBXMRUG0P/XnMqonceSOnj4FETCJI6x2yslNfO93qvpAdsYbt+117m/ASkV9UaXWZr7kVbm7/5xknF3P/uKK+e4fOUSEUMcw7Tvg5mTTJGmCp4wkYiQYdN0bp6Gs6NqVbG1lYe9q5NVYA6vw28lQ2jQmYqIyP+09NnnP5Qilu7z4CuePWQGjxec+pHpsc/FyhD+VocnGmg4zJwWR50Bmxzg6rlMwzqFU6CHIMjz6kJxNMVVIJFGg4LcVSPzKP6+gKFGj346LJZ5vV3D1s9BkZ1pL0O0cvUXPOhUDkC7hPjJYNMFIO06XTmQhnHuM3YucgBTv6dIyIAHMFEW2k3rUfqIX3x1vC1QYHvTJfWIF16EmgSMbzUtNFjDM0vdoEykzIRmyHeVdBw922wviX9gkEWbBqcKeMPvmnY7ZdbHyn1NSotN8RFR2hazq72Oc=
addons:
  sauce_connect: true
language: node_js
node_js:
  - 0.12
script: >
  ./node_modules/.bin/mocha test/test.js
cache:
  directories:
    - node_modules
notifications:
  email:
    on_success: change
    on_failure: always
