before-install:
- export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
env:
  global:
    - SELENIUM_HOST=hub.browserstack.com
    - SELENIUM_PORT=80
    - BS_AUTOMATE_PROJECT="$TRAVIS_REPO_SLUG"
    - BS_AUTOMATE_BUILD="Travis ($TRAVIS_BUILD_NUMBER) for $TRAVIS_REPO_SLUG"
addons:
  sauce_connect: true
language: node_js
node_js:
- 0.12
script: |
  ./node_modules/.bin/shortcake test-ci
cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    secure: rh3aLhMvUrugv+V1w3ZJxvRQlMH62zGQz02PZDLJFS9k9qe99J/KRIHvsPFw7cQXzDO7uWpX3KKKk+q5qYRF6bskD7n9S10OYnjNe9aDm/rWbiEbjmuWOm1K56C9EjqUCNLygx26Xz9G75qxMqoJDSOMRmwdhbbrwZRo188Pa9OoDuxxHQ7NSSR8MnqRpOXbDBKU1Maxye5WzP3jXxXKmRWP+yx8B76B+74M/NkXrFAyEM0kbJsqBXONeF+WNydftZHwJ1BXPLG3tIzV0PjLcVpBT3HRjgX8aA4775vWurcAwiAgyM6fWRZJRkQnxjPVzY5Ncm2UZMWQFXbd71LB/IzfUIJ5TqdmcVmEQfPOkrhd+eLYoiVte1/lB5Oxg6u4qlMdUVdceWZQfcjQ437q5ZuKKWYn33uFasqAyGOQwhPXdKeOT9lx4uLJ+vCnboRJKmOkx648TrdD9l8/Tl9u0x2Ol3XZPBh1Dj3Xajn5dH4NbQlttH070yvg2xQiWqNVnbqtiGU0uvXbMDJGC2VVFStYCY9k7rOktgSnb0g+sJse/rW63EHr29lSv1/nY/4XYzORQUtrNUMQ2fWWz4OHWAwQ08FvQ9gzLF/oxY5IyTi0UEu5xN8eqZs6cv1Bv4NHQ9M1TWctbQHiEUcBhPV2GQEsjbJZLBXbS2x5Z/ntKSI=
