before-install:
- export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
- wget http://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip
- unzip BrowserStackLocal-linux-x64.zip
- ./BrowserStackLocal $BROWSERSTACK_KEY localhost,3333,0 > /dev/null &
- sleep 10
env:
  global:
  - SELENIUM_HOST=hub.browserstack.com
  - SELENIUM_PORT=80
  - BS_AUTOMATE_PROJECT="$TRAVIS_REPO_SLUG"
  - BS_AUTOMATE_BUILD="Travis ($TRAVIS_BUILD_NUMBER) for $TRAVIS_REPO_SLUG"
  - secure: urpsKHz1kzsijD5tG6M/VA4Xd2bOGmyP1Ty5Tq2KXmUCnfFqLsPIK1wcGSNNXJKSMjJYbNIaGeZsufP8f9mEuvSrrpK0CF5hWynUy4T2ajgejWMXgeHSsxbFzLBJjqt+y1+RI21RbpEU96E/uLjOA6KPzLEWxrZrP7omGxQnby+yU8rmRquQ4xxvetGTzAL1F5EB26f6jIKCm4FmaTK7dxmiKVUpAI/Z4M4qCzwtRllU/CySwHgyorAfKGSmt6GU8EvUhe231r0VTD5YjFs60LlhipLg8IDnjdtN1GKzjQAEa3cnwmPjGreb5U/Zbc1Lzn/PeXY57aCOFmxtBWW2s+IZjlun38lwiDeSzrYLHqo0j5MZd306nlAQ1ngGi6PVqbfhYmUiRTFPUEe5woSoRkbrbYou73o6R2zdxKBFtNGuquLt2yw0onaGhzvTMfekmINKYTLAw9CfpAXXgnvsn2qe5S/bCem1YVNLv//+Qkyp/52bgO6Ot/BO1Cve1Xnw02DzkJT03St4r7Q2915C1oM6RffI3jScedh/cDE95SofAgg1JsP8PaUCpzUDzhTJNMz//kkOlUOV0O3ae1tp4ST91xclj7Nc9fRxP2i+QNWzWZjI70XvzJ1rnl8reuEM7lbvDV4093DFH3EdGhf95CqIQ7hMAKojzzeChvel9pk=
  - secure: ULro54AvAIwgFZLOYzj3FGk4/azs7YQd6IrqALMeAJIAD2MoQJk7N8P5FoWBBQXDjsyex/FMhfWnMaVXpMtSzsQt9yixH9mq/OsMNtqFocNsNt/lGH/FboHFKCe5LFME+5W+3Fhm3O/bwVnZg2/7La90G72po1uEALsTL+I11JNrMWacwUP0UkD6jKEsU97D2Rr+kLmwuw5pnVN1x+bNr2hVY0bHAkcvDzX9S83P0pounSa0AfBmrn7ay7kOUqNAZhJz0TXg3efgkccEcTIMg7Db+Zzj13UvzfkQIAsugwTWcOIQ1iiNtifH37j5xoxQn71W47fE+3mXGggSy1FLFE/ukBOhEq8+LZf3wIgNlpJcPbtlwvX8Btqzvp/d3/cLugz5Wh5buY5VCqNd6R0y9G7pXymou6wlCHlRg+/GYkZ05byyN78JgahM1KnRDsBErdGnppRRSYdS1ASH1+2De19PW1OvqmbxTmdnQsv8W4UPrSJK1AvFiYcAjL7O+6cu6Wh2sjCsqmK+EY6W8OCzlCyVmVp67Xgd/4LBx9e6ILX3unPdlPFv/SMdYxXlx1afehtQULtA+6MnpjQmGcda4XndER81spvS4+iQu1CQA8gEoZ7xigbC71VDmgjVCbtXElWcqJraFZP6U7g524HIcWhAQiq4d6kDcs1S/GH2g40=
language: node_js
node_js:
- 0.12
script: |
  ./node_modules/.bin/shortcake test-ci
cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    secure: rh3aLhMvUrugv+V1w3ZJxvRQlMH62zGQz02PZDLJFS9k9qe99J/KRIHvsPFw7cQXzDO7uWpX3KKKk+q5qYRF6bskD7n9S10OYnjNe9aDm/rWbiEbjmuWOm1K56C9EjqUCNLygx26Xz9G75qxMqoJDSOMRmwdhbbrwZRo188Pa9OoDuxxHQ7NSSR8MnqRpOXbDBKU1Maxye5WzP3jXxXKmRWP+yx8B76B+74M/NkXrFAyEM0kbJsqBXONeF+WNydftZHwJ1BXPLG3tIzV0PjLcVpBT3HRjgX8aA4775vWurcAwiAgyM6fWRZJRkQnxjPVzY5Ncm2UZMWQFXbd71LB/IzfUIJ5TqdmcVmEQfPOkrhd+eLYoiVte1/lB5Oxg6u4qlMdUVdceWZQfcjQ437q5ZuKKWYn33uFasqAyGOQwhPXdKeOT9lx4uLJ+vCnboRJKmOkx648TrdD9l8/Tl9u0x2Ol3XZPBh1Dj3Xajn5dH4NbQlttH070yvg2xQiWqNVnbqtiGU0uvXbMDJGC2VVFStYCY9k7rOktgSnb0g+sJse/rW63EHr29lSv1/nY/4XYzORQUtrNUMQ2fWWz4OHWAwQ08FvQ9gzLF/oxY5IyTi0UEu5xN8eqZs6cv1Bv4NHQ9M1TWctbQHiEUcBhPV2GQEsjbJZLBXbS2x5Z/ntKSI=
